apiVersion: v1
kind: Service
metadata:
  name: trtarsiv
  labels:
    app: trtarsiv
  annotations:
    maesh.containo.us/traffic-type: "http"
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: trtarsiv
  selector:
    app: trtarsiv